@startuml class-diagram

hide empty members

!theme blueprint
!pragma useIntermediatePackages false

package "io.github.masmangan.assis" {
class "io.github.masmangan.assis.AssisApp" <<final>> {
  - <<create>> AssisApp()
  + main(args : String[]) : void {static}
}
class "io.github.masmangan.assis.GenerateClassDiagram" {
  - {static} DOCS_UML_CLASS_DIAGRAM_PUML : String {final}
  - {static} SRC_MAIN_JAVA : String {final}
  - {static} logger : Logger {final}
  - <<create>> GenerateClassDiagram()
  - versionOrDev() : String {static}
  + generate() : void {static}
  + generate(src : Path, out : Path) : void {static}
  - assisLine() : String {static}
  - addHeader(pw : PrintWriter) : void {static}
  - getClassifier(t : TypeInfo) : String {static}
  - writePackages(pw : PrintWriter, byPkg : Map<String,List<TypeInfo>>, types : Map<String,TypeInfo>) : void {static}
  - writeEnumConstants(pw : PrintWriter, t : TypeInfo) : void {static}
  - writeConstructors(pw : PrintWriter, t : TypeInfo) : void {static}
  - writeMethods(pw : PrintWriter, t : TypeInfo) : void {static}
  - writeRelationships(pw : PrintWriter, types : Map<String,TypeInfo>) : void {static}
  - writeAssociations(pw : PrintWriter, types : Map<String,TypeInfo>, t : TypeInfo) : void {static}
  - displayTypeFrom(vd : VariableDeclarator) : String {static}
  - assocTypeFrom(types : Map<String,TypeInfo>, owner : TypeInfo, vd : VariableDeclarator) : String {static}
  - writeFields(pw : PrintWriter, types : Map<String,TypeInfo>, t : TypeInfo) : void {static}
  - getVisibility(fr : FieldRef) : String {static}
  - getVisibility(fr : MethodRef) : String {static}
  - getVisibility(cr : ConstructorRef) : String {static}
  - visibility(n : NodeWithAccessModifiers<?>) : String {static}
  - writeImplements(pw : PrintWriter, types : Map<String,TypeInfo>, t : TypeInfo) : void {static}
  - writeExtends(pw : PrintWriter, types : Map<String,TypeInfo>, t : TypeInfo) : void {static}
  - sortPackagesByName(byPkg : Map<String,List<TypeInfo>>) : Map<String,List<TypeInfo>> {static}
  - writeDiagram(out : Path, types : Map<String,TypeInfo>) : void {static}
  - scanSources(src : Path, types : Map<String,TypeInfo>) : void {static}
  - scanType(types : Map<String,TypeInfo>, cu : CompilationUnit, pkg : String, td : TypeDeclaration<?>) : void {static}
  - scanClassOrInterface(info : TypeInfo, cid : ClassOrInterfaceDeclaration) : void {static}
  - getFlags(method : MethodDeclaration) : String {static}
  - addFooter(pw : PrintWriter) : void {static}
  - simpleName(qname : String) : String {static}
  - resolveTypeName(types : Map<String,TypeInfo>, owner : TypeInfo, name : String) : String {static}
}
}

left to right direction

' Generated with ASSIS (Java -> UML)
' https://github.com/masmangan/assis

@enduml
