@startuml class-diagram

hide empty members
!theme blueprint
!pragma useIntermediatePackages false

package "io.github.masmangan.assis" {
class "io.github.masmangan.assis.GenerateClassDiagram" {
  - {static} DOCS_UML_CLASS_DIAGRAM_PUML : String {final}
  - {static} SRC_MAIN_JAVA : String {final}
  - {static} logger : Logger {final}
  - versionOrDev() : String {static}
  + generate() : void {static}
  + generate(src : Path, out : Path) : void {static}
  - assisLine() : String {static}
  - addHeader(pw : PrintWriter) : void {static}
  - getClassifier(t : TypeInfo) : String {static}
  - writePackages(pw : PrintWriter, byPkg : Map<String,List<TypeInfo>>, types : Map<String,TypeInfo>, root : SourceRoot) : void {static}
  - writeMethods(pw : PrintWriter, types : Map<String,TypeInfo>, t : TypeInfo) : void {static}
  - writeRelationships(pw : PrintWriter, types : Map<String,TypeInfo>, root : SourceRoot) : void {static}
  - writeAssociations(pw : PrintWriter, types : Map<String,TypeInfo>, t : TypeInfo) : void {static}
  - displayTypeFrom(vd : com.github.javaparser.ast.body.VariableDeclarator) : String {static}
  - assocTypeFrom(types : Map<String,TypeInfo>, owner : TypeInfo, fd : FieldDeclaration, vd : com.github.javaparser.ast.body.VariableDeclarator) : String {static}
  - writeFields(pw : PrintWriter, types : Map<String,TypeInfo>, t : TypeInfo) : void {static}
  - getVisibility(fr : FieldRef) : String {static}
  - getVisibility(fr : MethodRef) : String {static}
  - writeImplements(pw : PrintWriter, types : Map<String,TypeInfo>, t : TypeInfo) : void {static}
  - writeExtends(pw : PrintWriter, types : Map<String,TypeInfo>, t : TypeInfo) : void {static}
  - writeDiagram(out : Path, types : Map<String,TypeInfo>, root : SourceRoot) : void {static}
  - scanSources(src : Path, types : Map<String,TypeInfo>) : SourceRoot {static}
  - scanType(types : Map<String,TypeInfo>, cu : CompilationUnit, pkg : String, td : TypeDeclaration<?>) : void {static}
  - scanClassOrInterface(info : TypeInfo, cid : ClassOrInterfaceDeclaration) : void {static}
  - getFlags(method : MethodDeclaration) : String {static}
  - addFooter(pw : PrintWriter) : void {static}
  - simpleName(qname : String) : String {static}
  - resolveTypeName(types : Map<String,TypeInfo>, owner : TypeInfo, name : String) : String {static}
}
enum "io.github.masmangan.assis.Modifier" {
}
class "io.github.masmangan.assis.AssisApp" <<final>> {
  + main(args : String[]) : void {static}
}
enum "io.github.masmangan.assis.Kind" {
}
}

left to right direction

center footer
Generated with ASSIS (Java -> UML) at 2025-12-23T23:28:51Z
https://github.com/masmangan/assis
end footer

@enduml
