/*
 * Copyright (c) 2025-2026, Marco Mangan. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 */

package io.github.masmangan.assis.cli;

import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import io.github.masmangan.assis.GenerateClassDiagram;

/**
 * The {@code AssisApp} class is the PlantUML diagram generator entry point.
 */
public final class AssisApp {

    private static final Logger LOG = Logger.getLogger(AssisApp.class.getName());

    /**
     * Default documentation path (PlantUML/Jebbs convention).
     */
    static final String DOCS_UML_CLASS_DIAGRAM_PUML = "docs/diagrams/src/class-diagram.puml";

    private AssisApp() {}

    public static void main(String[] args) {
    	
        int code = run(args, System.out, System.err);
        System.exit(code);
    }

    /**
     * Test-friendly runner.
     *
     * @return exit code (0 success, non-zero failure)
     */
    static int run(String[] args, PrintStream out, PrintStream err) {
        final CliArgs cli;
        try {
            cli = CliArgs.parse(args);
        } catch (IllegalArgumentException e) {
            err.println(e.getMessage());
            return 1;
        }

        if (cli.mode == CliArgs.Mode.HELP) {
            out.println(CliArgs.usage());
            return 0;
        }

        if (cli.mode == CliArgs.Mode.VERSION) {
            // Single source of truth: core knows the version.
            out.println("ASSIS " + GenerateClassDiagram.versionOrDev());
            return 0;
        }

        Path src;
        try {
            src = SourceLocator.resolve(cli.sourcePath);
        } catch (Exception e) {
            err.println("ERROR: " + e.getMessage());
            return 2;
        }

        final Path outFile = (cli.outPath != null) ? cli.outPath : Path.of(DOCS_UML_CLASS_DIAGRAM_PUML);

        try {
            Files.createDirectories(outFile.toAbsolutePath().getParent());

            // Backup if output exists (manual edits are plausible for .puml).
            Path bak = backupIfExists(outFile);
            if (bak != null) {
                LOG.info(() -> "Backup created: " + bak.toAbsolutePath());
            }

            // Generate to temp and then replace.
            Path tmp = outFile.resolveSibling(outFile.getFileName().toString() + ".tmp");
            Files.deleteIfExists(tmp);

            LOG.info(() -> "Generating diagram from: " + src.toAbsolutePath());
            LOG.info(() -> "Writing diagram to: " + outFile.toAbsolutePath());

            GenerateClassDiagram.generate(src, tmp);

            // (2) Inject traceability header into the generated .puml (no new knobs)
            injectTraceabilityHeader(tmp, src);

            moveReplacing(tmp, outFile);

            return 0;
        } catch (Exception e) {
            err.println("ERROR: " + e.getMessage());
            return 3;
        }
    }

    /**
     * Creates a backup next to the output file if it already exists.
     * Backup name MUST NOT end with ".puml" to avoid being treated as source by tooling.
     *
     * Example: class-diagram.puml.bak-20260102-093012
     */
    static Path backupIfExists(Path outFile) throws IOException {
        if (!Files.exists(outFile) || !Files.isRegularFile(outFile)) {
            return null;
        }

        String ts = OffsetDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss"));
        Path bak = outFile.resolveSibling(outFile.getFileName().toString() + ".bak-" + ts);

        Files.copy(outFile, bak, StandardCopyOption.COPY_ATTRIBUTES);
        return bak;
    }

    /**
     * Inserts a small comment block with provenance information.
     * We try to place it right after @startuml when present.
     */
    static void injectTraceabilityHeader(Path pumlFile, Path src) throws IOException {
        List<String> lines = Files.readAllLines(pumlFile);

        String ts = OffsetDateTime.now().format(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        String version = GenerateClassDiagram.versionOrDev();

        List<String> header = List.of(
            "' Generated by ASSIS " + version,
            "' Source path: " + src.toAbsolutePath(),
            "' Generated at: " + ts
        );

        int insertAt = 0;
        for (int i = 0; i < lines.size(); i++) {
            if (lines.get(i).trim().startsWith("@startuml")) {
                insertAt = i + 1;
                break;
            }
        }

        ArrayList<String> out = new ArrayList<>(lines.size() + header.size() + 1);
        out.addAll(lines.subList(0, insertAt));
        out.addAll(header);
        out.addAll(lines.subList(insertAt, lines.size()));

        Files.write(pumlFile, out);
    }

    private static void moveReplacing(Path from, Path to) throws IOException {
        try {
            Files.move(from, to,
                StandardCopyOption.REPLACE_EXISTING,
                StandardCopyOption.ATOMIC_MOVE);
        } catch (IOException atomicNotSupported) {
            Files.move(from, to,
                StandardCopyOption.REPLACE_EXISTING);
        }
    }
}