@startuml class-diagram
hide empty members
!theme blueprint
package "io.github.masmangan.assis" {
class AssisApp
class GenerateClassDiagram
}

left to right direction

center footer
Generated with ASSIS (Java -> UML) at: 2025-12-15T17:41:47.97043617Z
https://github.com/masmangan/javaparser-to-plantuml
end footer

@enduml
