/*
 * Copyright (c) 2025-2026, Marco Mangan. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 */

package io.github.masmangan.assis.internal;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;

import io.github.masmangan.assis.AssisInfo;
import io.github.masmangan.assis.GenerateClassDiagram;
import io.github.masmangan.assis.io.PlantUMLWriter;

/**
 *
 */
public final class ClassDiagramGeneration {
	private static final Logger logger = Logger.getLogger(GenerateClassDiagram.class.getName());

	private final Path out;
	private final DeclaredIndex idx;

	/**
	 *
	 * @param out
	 * @param idx
	 */
	public ClassDiagramGeneration(Path out, DeclaredIndex idx) {
		super();
		this.out = out;
		this.idx = idx;
	}

	/**
	 * Writes common PlantUML directives used by ASSIS diagrams.
	 *
	 * <p>
	 * Current directives include:
	 * <ul>
	 * <li>{@code hide empty members}</li>
	 * <li>{@code !theme blueprint}</li>
	 * <li>{@code !pragma useIntermediatePackages false}</li>
	 * </ul>
	 *
	 * @param pw writer to receive directives; must not be {@code null}
	 * @throws NullPointerException if {@code pw} is {@code null}
	 */
	private static void writeHeader(final PlantUMLWriter pw) {
		pw.println();
		pw.println("mainframe class diagram (cd)");
		pw.println();
		pw.println("hide empty members");
		pw.println();
		pw.println("!theme blueprint");
		pw.println("!pragma useIntermediatePackages false");
		pw.println();
		pw.println("left to right direction");
		pw.println();
		pw.println("' Diagram generated by ASSIS (%s).".formatted(AssisInfo.versionOrDev()));
		pw.println("' https://github.com/masmangan/assis");
		pw.println();
	}

	/**
	 * Writes the PlantUML diagram to a file.
	 *
	 * <p>
	 * This method emits:
	 * <ol>
	 * <li>Diagram start and header</li>
	 * <li>Packages and types</li>
	 * <li>Relationships (inheritance, nesting, associations)</li>
	 * <li>Layout directives</li>
	 * <li>Diagram end</li>
	 * </ol>
	 *
	 * <p>
	 * The output is written using UTF-8.
	 *
	 * @param out output file path; must not be {@code null}
	 * @param idx index containing declared types and package grouping; must not be
	 *            {@code null}
	 * @throws IOException
	 */
	public void run() throws IOException {
		// Order matters: emit types first so later relations can refer to them
		// Stronger relations first, then dependencies
		try (PlantUMLWriter pw = new PlantUMLWriter(
				new PrintWriter(Files.newBufferedWriter(out, StandardCharsets.UTF_8)));) {
			pw.beginDiagram("class-diagram");

			writeHeader(pw);

			writeTypes(pw);

			pw.println();
			pw.println();

			writeStructuralRelations(pw);

			writeDependencies(pw);
			pw.println();

			pw.endDiagram("class-diagram");

		} catch (IOException e) {
			logger.log(Level.WARNING, () -> "Error writing diagram file: " + e.getLocalizedMessage());
			throw e;
		}
	}

	/**
	 *
	 * @param idx
	 * @param pw
	 */
	private void writeDependencies(PlantUMLWriter pw) {
		DependencyContext context = new DependencyContext(idx, pw);
		CollectDependenciesVisitor dependenciesVisitor = new CollectDependenciesVisitor();
		for (var td : idx.typesInIndexOrder()) {
			// String pkgDerived = DeclaredIndex.derivePkg(td);
			// String fqnDerived = DeclaredIndex.deriveFqnDollar(td);
			if (DeclaredIndex.isTopLevel(td)) {
				td.accept(dependenciesVisitor, context);
			}
		}
	}

	/**
	 *
	 * @param idx
	 * @param pw
	 */
	private void writeStructuralRelations(PlantUMLWriter pw) {
		new CollectRelationshipsVisitor(idx, pw).emitAll();
	}

	/**
	 *
	 * @param idx
	 * @param pw
	 */
	private void writeTypes(PlantUMLWriter pw) {
		for (var pkg : idx.packagesInIndexOrder()) {
			if (!pkg.isEmpty()) {
				pw.println();
				pw.beginPackage(pkg);
			}
			for (var td : idx.typesInPackageOrder(pkg)) {
				String fqn = DeclaredIndex.deriveFqnDollar(td);
				new CollectTypesVisitor(idx, pkg, pw).emitType(fqn, td);
			}
			if (!pkg.isEmpty()) {
				pw.println();
				pw.endPackage(pkg);
			}
		}
	}
}
