/*
 * Copyright (c) 2025-2026, Marco Mangan. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 */

package io.github.masmangan.assis.internal;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import io.github.masmangan.assis.AssisInfo;
import io.github.masmangan.assis.io.PlantUMLWriter;

/**
 * Controls the process of a class diagram generation. *
 * <p>
 * This process emits:
 * <ol>
 * <li>Diagram start and header</li>
 * <li>Packages and types</li>
 * <li>Structural relationships (inheritance, nesting, association)
 * <li>Uses relationships (dependency)</li>
 * <li>Diagram end</li>
 * </ol>
 *
 * <p>
 * The output file is written using UTF-8.
 *
 */
public final class ClassDiagramGeneration {

	private final Path outFile;

	private final DeclaredIndex idx;

	/**
	 * Generation will output a file from an index of parsed types.
	 *
	 * @param outFile output file path; must not be {@code null}
	 * @param idx     index containing declared types and package grouping; must not
	 *                be {@code null}
	 */
	public ClassDiagramGeneration(final Path outFile, final DeclaredIndex idx) {
		super();
		this.outFile = outFile;
		this.idx = idx;
	}

	/**
	 * Writes the PlantUML diagram to a file.
	 *
	 * @throws IOException
	 */
	public void run() throws IOException {
		// Order matters: emit types first so later relations can refer to them
		// Stronger relations first, then dependencies
		try (PlantUMLWriter pw = new PlantUMLWriter(
				new PrintWriter(Files.newBufferedWriter(outFile, StandardCharsets.UTF_8)));) {
			pw.beginDiagram("class-diagram");

			writeHeader(pw);

			writeTypes(pw);

			pw.println();
			pw.println();

			EdgeRegistry er = new EdgeRegistry();

			writeStructuralRelations(pw, er);

			writeDependencies(pw, er);
			pw.println();

			pw.endDiagram("class-diagram");

		} catch (IOException e) {
			throw new IllegalStateException("Error writing diagram file", e);
		}
	}

	private static void writeHeader(final PlantUMLWriter pw) {
		pw.println();
		pw.println("mainframe class diagram (cd)");
		pw.println();
		pw.println("hide empty members");
		pw.println();
		pw.println("!theme blueprint");
		pw.println("!pragma useIntermediatePackages false");
		pw.println();
		pw.println("left to right direction");
		pw.println();
		pw.println("' Diagram generated by ASSIS (%s).".formatted(AssisInfo.versionOrDev()));
		pw.println("' https://github.com/masmangan/assis");
		pw.println();
	}

	private void writeTypes(PlantUMLWriter pw) {
		for (var pkg : idx.packagesInIndexOrder()) {
			if (!pkg.isEmpty()) {
				pw.println();
				pw.beginPackage(pkg);
			}
			for (var td : idx.typesInPackageOrder(pkg)) {
				new CollectTypesVisitor(idx, pkg, pw).emitType(td);
			}
			if (!pkg.isEmpty()) {
				pw.println();
				pw.endPackage(pkg);
			}
		}
	}

	private void writeStructuralRelations(PlantUMLWriter pw, EdgeRegistry er) {
		new CollectRelationshipsVisitor(idx, pw, er).emitAll();
	}

	private void writeDependencies(PlantUMLWriter pw, EdgeRegistry er) {
		DependencyContext context = new DependencyContext(idx, pw, er);
		CollectDependenciesVisitor dependenciesVisitor = new CollectDependenciesVisitor();
		for (var td : idx.typesInIndexOrder()) {
			if (DeclaredIndex.isTopLevel(td)) {
				td.accept(dependenciesVisitor, context);
			}
		}
	}

}
